main() checkpoint 1
func1() checkpoint 1
func2() checkpoint 1
Exception catched: my exception
